### PR TITLE
Fix bug on Participants

### PR DESCRIPTION
**Pull request by jefflau**

### CODE REVIEW

**Comment by noblocknoparty-devs** [comment]
PR deployed at: https://pr53-app-noblocknoparty.surge.sh

**Comment by jefflau** [comment]
I think this PR is specifically for fixing the bug that it is showing the incorrect information and should be merged ASAP, I think new UX changes we should discuss post devcon and prioritise them together unless they are high priority for a specific event we are doing this week.

**Comment by jefflau** [comment]
Generally I think it's a good idea though

**Comment by makoto** [comment]
@hiddentao let's handle it one PR at a time

**Pull request merged**
