### PR TITLE
Ability to add admins to an event

### PR DESCRIPTION
**Pull request by hiddentao**

### CODE REVIEW

**Comment by noblocknoparty-devs** [comment]
PR deployed at: https://pr32-app-noblocknoparty.surge.sh

**Comment by noblocknoparty-devs** [comment]
PR deployed at: https://pr32-app-noblocknoparty.surge.sh

**Comment by makoto** [comment]
Can we not pass an array of addresses so that we can grant in one transaction (comma separated etc)? Would be ideal when gas price is relatively high

**Comment by noblocknoparty-devs** [comment]
PR deployed at: https://pr32-app-noblocknoparty.surge.sh

**Comment by noblocknoparty-devs** [comment]
PR deployed at: https://pr32-app-noblocknoparty.surge.sh

**Comment by noblocknoparty-devs** [comment]
PR deployed at: https://pr32-app-noblocknoparty.surge.sh

**Comment by noblocknoparty-devs** [comment]
PR deployed at: https://pr32-app-noblocknoparty.surge.sh

**Pull request merged**
